[2023-12-06T23:46:25.136+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag2.download_data scheduled__2023-07-02T00:00:00+00:00 [queued]>
[2023-12-06T23:46:25.145+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag2.download_data scheduled__2023-07-02T00:00:00+00:00 [queued]>
[2023-12-06T23:46:25.145+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-06T23:46:25.319+0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): download_data> on 2023-07-02 00:00:00+00:00
[2023-12-06T23:46:25.322+0500] {standard_task_runner.py:57} INFO - Started process 30733 to run task
[2023-12-06T23:46:25.325+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag2', 'download_data', 'scheduled__2023-07-02T00:00:00+00:00', '--job-id', '660', '--raw', '--subdir', 'DAGS_FOLDER/airflow_dag.py', '--cfg-path', '/tmp/tmpo99w8mvw']
[2023-12-06T23:46:25.326+0500] {standard_task_runner.py:85} INFO - Job 660: Subtask download_data
[2023-12-06T23:46:25.511+0500] {task_command.py:416} INFO - Running <TaskInstance: etl_dag2.download_data scheduled__2023-07-02T00:00:00+00:00 [running]> on host amina-HP-ProBook-450-G2
[2023-12-06T23:46:25.905+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='amina_bibi' AIRFLOW_CTX_DAG_ID='etl_dag2' AIRFLOW_CTX_TASK_ID='download_data' AIRFLOW_CTX_EXECUTION_DATE='2023-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-02T00:00:00+00:00'
[2023-12-06T23:46:29.350+0500] {logging_mixin.py:154} INFO - Access denied with the following error:
[2023-12-06T23:46:29.351+0500] {logging_mixin.py:154} WARNING -  	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 
[2023-12-06T23:46:29.351+0500] {logging_mixin.py:154} WARNING - You may still be able to access the file from the browser:
[2023-12-06T23:46:29.351+0500] {logging_mixin.py:154} WARNING - 
	 https://drive.google.com/uc?id=10iZbAEEw7t8rtaD39OiuE9qPB8eSF3OJ 
[2023-12-06T23:46:29.351+0500] {python.py:194} INFO - Done. Returned value was: None
[2023-12-06T23:46:29.359+0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_dag2, task_id=download_data, execution_date=20230702T000000, start_date=20231206T184625, end_date=20231206T184629
[2023-12-06T23:46:29.753+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-06T23:46:29.775+0500] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
