[2023-12-06T21:48:17.401+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag2.download_data scheduled__2023-01-08T00:00:00+00:00 [queued]>
[2023-12-06T21:48:17.412+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag2.download_data scheduled__2023-01-08T00:00:00+00:00 [queued]>
[2023-12-06T21:48:17.413+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-06T21:48:17.528+0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): download_data> on 2023-01-08 00:00:00+00:00
[2023-12-06T21:48:17.531+0500] {standard_task_runner.py:57} INFO - Started process 8578 to run task
[2023-12-06T21:48:17.534+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag2', 'download_data', 'scheduled__2023-01-08T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/airflow_dag.py', '--cfg-path', '/tmp/tmph59avjdo']
[2023-12-06T21:48:17.535+0500] {standard_task_runner.py:85} INFO - Job 18: Subtask download_data
[2023-12-06T21:48:17.655+0500] {task_command.py:416} INFO - Running <TaskInstance: etl_dag2.download_data scheduled__2023-01-08T00:00:00+00:00 [running]> on host amina-HP-ProBook-450-G2
[2023-12-06T21:48:17.879+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='amina_bibi' AIRFLOW_CTX_DAG_ID='etl_dag2' AIRFLOW_CTX_TASK_ID='download_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-08T00:00:00+00:00'
[2023-12-06T21:48:21.910+0500] {logging_mixin.py:154} INFO - Access denied with the following error:
[2023-12-06T21:48:21.910+0500] {logging_mixin.py:154} WARNING -  	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 
[2023-12-06T21:48:21.910+0500] {logging_mixin.py:154} WARNING - You may still be able to access the file from the browser:
[2023-12-06T21:48:21.910+0500] {logging_mixin.py:154} WARNING - 
	 https://drive.google.com/uc?id=10iZbAEEw7t8rtaD39OiuE9qPB8eSF3OJ 
[2023-12-06T21:48:21.911+0500] {python.py:194} INFO - Done. Returned value was: None
[2023-12-06T21:48:22.096+0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_dag2, task_id=download_data, execution_date=20230108T000000, start_date=20231206T164817, end_date=20231206T164822
[2023-12-06T21:48:22.240+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-06T21:48:22.505+0500] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
